name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        continue-on-error: true
        with:
          checkstyle_version: 10.17.0
          checkstyle_config: 'mod_v10.17.0_google_checks.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Checkstyle'

      - name: Run tests
        run: mvn test
        env:
          ACCESS_OPTIONS: |-
            baseURL=${{ secrets.BASE_URL }};
            userEmail=${{ secrets.USER_EMAIL }};
            userPassword=${{ secrets.USER_PASSWORD }}
          BROWSER_OPTIONS: |-
            browserType=chromium;
            viewportWidth=1920;
            viewportHeight=1080;
            headlessMode=true;
            slowMoMode=0;
            tracingMode=true;
            videoMode=true
          CI_RUN: true

      - name: Attach artefacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Artefacts
          path: target/artefact/
          retention-days: 1

      - name: Build Allure report with history
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results

      - name: Store generated report
        id: deployment
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: allure-report

  publish-report:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run-tests
    if: always()
    name: Report publication

    steps:
      - name: Deploy to gitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
